"""empty message

Revision ID: 2d346b0ceed9
Revises:
Create Date: 2020-04-22 23:33:15.646567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d346b0ceed9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('actor', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('actor', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('actor', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('actor', 'name_1')
    op.drop_column('actor', 'age_1')
    op.drop_column('actor', 'id_1')
    op.drop_column('actor', 'gender_1')
    op.add_column('movie', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('movie', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movie', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('movie', 'title_1')
    op.drop_column('movie', 'id_1')
    op.drop_column('movie', 'release_date_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date_1', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('id_1', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('movie', sa.Column('title_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'title')
    op.drop_column('movie', 'release_date')
    op.drop_column('movie', 'id')
    op.add_column('actor', sa.Column('gender_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actor', sa.Column('id_1', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('actor', sa.Column('age_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actor', sa.Column('name_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('actor', 'name')
    op.drop_column('actor', 'id')
    op.drop_column('actor', 'gender')
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###
